### ISSUE TITLE
Feedback from Broadcom #2

### ISSUE THREAD

**Issue by tbiat** [AOMediaCodec/av1-mpeg2-ts#2]
Feedback from Broadcom:
We know this has always come up with people saying it strictly isn't needed but it makes so many things easier to have the frame rate is explicitly coded in the elementary stream.for minimal cost so we have been pushing application specs (for other specs as well) to require timing_info and equal_picture_interval=1.

**Comment by tbiat** [comment]
Feedback from ATEME : 
We do understand the issue, and it would make sense to mandate such constraints. However, AV1 specification does not force to write the timing_info nor to set equal_picture_interval to 1. Furthermore, the AV1-in-MPEG2TS specification in not an applicative specification, it is more the role of DVB/ATSC to force the value of such parameters. We belive that this remark makes sense, but such constraints should be defined in the DVB specification rather than this one.

**Comment by cconcolato** [comment]
It is indeed covered in DVB. Can we close this issue?

**Comment by wadekwan** [comment]
Agree this is addressed in the current draft for DVB where there is text requiring timing_info_present_flag to be equal to 1.  

The feedback provided was to always include frame rate info when AV1 is encapsulated in TS as we believe there is a lot of benefit to AV1 interop in general and not just for DVB to have this same requirement in the AV1 in TS spec.  

Knowing there is a fixed frame rate signaled is different than not being told as even if a decoder receives pictures where the picture interval is repeatedly the same, the decoder must treat subsequent pictures as a variable frame rate stream because it does not know if it will change over time.

The downside for not including similar text in this base spec is it is hard to expect other application standards to understand the subtleties and pick up this constraint like DVB did without someone present who has detailed knowledge of the AV1 codec.  

So we believe there still is value to include a similar clause that is in the DVB draft to this TS spec but this topic was discussed before so if there is opposition to include it, then we can close this issue.

**Comment by tbiat** [comment]
The group decided to let applicative spec to be explicit on this.
